### ISSUE TITLE
create drop down menu to filter information by a specific network

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/analytics-dashboard#9] opened 2024-05-29 20:33 UTC
We should replace the current toggle for "Optimism Only" with a drop down menu allowing us to filter by any network that Giveth supports, including: 

- [ ] mainnet
- [ ] gnosis chain
- [ ] optimism
- [ ] polygon
- [ ] eth classic
- [ ] solana
- [ ] arbitrum
- [ ] base
- [ ] celo
- [ ] polygon zkevm

### projects count 
- include drop down menu for filtering by projects that have added receiving address for selected network
### Donors count
- include drop down menu for filtering by donors that have donated on the selected network

### Donations Count
- include drop down menu for filtering by donations that have been made on the selected network

### Total Donations ($)
- include drop down menu for filtering by usd value of donations that have been made on the selected network

**Comment by RamRamez** [comment] 2024-06-24 15:25
only one network can be chosen at a time, so it's not needed to filter by two or more networks like mainnet and Op, @divine-comedian is that right?

**Comment by divine-comedian** [comment] 2024-06-24 16:20
> only one network can be chosen at a time, so it's not needed to filter by two or more networks like mainnet and Op, @divine-comedian is that right?

yes correct - either filter by one specific network or with no filter, which looks across all netwroks. we won't need to worry about filtering across two or more networks.

**Comment by RamRamez** [comment] 2024-06-25 20:50
@maryjaf please test and verify

https://analytics-dashboard-git-9-add-dropdown-menu-givethio.vercel.app/

**Comment by maryjaf** [comment] 2024-06-26 11:48
I couldn't move it to Done I have no access on analytics-dashboard

**Comment by RamRamez** [comment] 2024-06-26 13:09
@MoeNick Could you please grant @maryjaf required permissions?

**Comment by divine-comedian** [comment] 2024-06-26 14:07
moved it to done! Where could I test it?

**Comment by ae2079** [comment] 2024-06-26 23:40
> moved it to done! Where could I test it?

You can test it by this link:
https://analytics-dashboard-git-9-add-dropdown-menu-givethio.vercel.app/
this is a preview of the analytics dashboard new changes with the staging data

**Comment by divine-comedian** [comment] 2024-06-27 13:32
> > moved it to done! Where could I test it?
> 
> You can test it by this link: https://analytics-dashboard-git-9-add-dropdown-menu-givethio.vercel.app/ this is a preview of the analytics dashboard's new changes with the staging data

Nice! two things 

1. Make sure Polygon zkEVM is included in the drop down list (Polygon and Polygon zkEVM are two separate chains FYI) 
2. Is it possible to create a preview link with production data?

**Comment by ae2079** [comment] 2024-06-27 17:06
> > > moved it to done! Where could I test it?
> > 
> > 
> > You can test it by this link: https://analytics-dashboard-git-9-add-dropdown-menu-givethio.vercel.app/ this is a preview of the analytics dashboard's new changes with the staging data
> 
> Nice! two things
> 
>     1. Make sure Polygon zkEVM is included in the drop down list (Polygon and Polygon zkEVM are two separate chains FYI)
> 
>     2. Is it possible to create a preview link with production data?

I added the Polygon zkEVM just now, and for the second one, I think @RamRamez should add it because I don't have access to vercel dashboard, and also, the changes on the impact-graph repo should be deployed on production before this

**Comment by divine-comedian** [comment] 2024-06-27 18:59
Thanks! I don't think the second point will block us to test. 

## To test 

- track chain specific stats relevant to this issue 
- create donations on staging on all test networks using tokens that we track a price for (usually ETH/native token always works)
- create projects with specific reciepient addresses
- edit projects and add recipient addresses for new networks
- check that the relevant numbers change as a result from the donations you made

### eth goerli (this way not work, chain is deprecated) 
- [ ] projects count
- [ ] donors count
- [ ] donations count
- [ ] total usd value donations count

### gnosis chain 
- [ ] projects count
- [ ] donors count
- [ ] donations count
- [ ] total usd value donations count

### optimism-sepolia 
- [ ] projects count
- [ ] donors count
- [ ] donations count
- [ ] total usd value donations count

### arbitrum-seplia 
- [ ] projects count
- [ ] donors count
- [ ] donations count
- [ ] total usd value donations count

### eth classic-mordor 
- [ ] projects count
- [ ] donors count
- [ ] donations count
- [ ] total usd value donations count

### celo-alfajores 
- [ ] projects count
- [ ] donors count
- [ ] donations count
- [ ] total usd value donations count

### base sepolia 
- [ ] projects count
- [ ] donors count
- [ ] donations count
- [ ] total usd value donations count

### polygon mainnet 
- [ ] projects count
- [ ] donors count
- [ ] donations count
- [ ] total usd value donations count

### polygon zkevm cardona 
- [ ] projects count
- [ ] donors count
- [ ] donations count
- [ ] total usd value donations count

### Solana
- [ ] projects count
- [ ] donors count
- [ ] donations count
- [ ] total usd value donations count

**Comment by ae2079** [comment] 2024-06-27 21:31
@divine-comedian 
I want to put the issue in the QA/UAT but I see you had put it to done, If we need a QA test, please update it

**Comment by divine-comedian** [comment] 2024-06-28 13:49
My Bad, I just asked @maryjaf  to take another look and confirm the QA

**Comment by maryjaf** [comment] 2024-06-30 08:17
This issue could be assigned to @LatifatAbdullahi  to get onboard more on donation flow and different chains on stg
@divine-comedian

**Comment by divine-comedian** [comment] 2024-06-30 23:56
Sure! @maryjaf can you support 

@LatifatAbdullahi to test this issue: 

On all staging networks you'll need to do a few interactions  check that analytics dashboard is correctly counting new interactions, make sure that as you do these interactions on the website that when you check the information on the analytics dashboard that you are filtering for the correct network. 

e.g. - make donation on polygon zkEVM testnet -> check on analytics dashboard, filtered by donations on polygon zkEVM only using the new dropdown menu feature.

Here's a brief list of the actions you may need to take on every test network we support to properly test this new feature:

1. add recipient addresses for new networks to a newly created project, check number goes up accordingly on "project count" 
2. make donations with a fresh user account, check donors and donations count goes up
3. make donations with an existing user account, check donations count goes up
4. using a token where the price is tracked, usually the native token, make donations with new or existing user, check usd value of donations increases accordingly

**bear in mind it could take up to 5 minutes for new interactions to be registered by the analytics dashboard.**

**Comment by LatifatAbdullahi** [comment] 2024-07-01 04:20
Noted

**Comment by LatifatAbdullahi** [comment] 2024-07-01 21:10
Test Status - In Progress

The Toggle for "Optimism Only" has now been replaced  with a drop down menu allowing Users  to filter by any network that 

![Pj](https://github.com/Giveth/analytics-dashboard/assets/112261242/8d8c3ca6-e196-4372-b737-b59c0d534680)
This image is same for there sections such as Donors count, Donations Count, Total Donations

**Gnosis chain**
 Projects count : Pass
 Donors count: Pass
 Donations count : Pass
 Total USD Value Donations count: Progress (The token donated(DRGIV) had USD value: 0, therefore would need to verify with another token )

Filtering Projects count using the "Gnosis Chain" returned expected result for the 3 sections.

**Comment by LatifatAbdullahi** [comment] 2024-07-01 21:25
@ae2079 @kkatusic

Currently experiencing a blocker with newly created Projects.
After successfully creating a Project, In order to make donations to the Projects, it has to be verified and listed. 
The issue is, After Verifying and updating the status to "Listed" , the Product status on the Project cards are updated, but it is not saved at the Giveth Admin section. Furthermore, when Users attempt to search for the Projects, even though the Project shows "Verified" and "Listed", the search results returns "There are no projects matching your search"
Note: I received Email Notifications that My Projects were Live and Listed, but when searched, it returns no results.

I was able to test certain functions with Projects I created last week but there is only little I can verify with old Projects

**Comment by LatifatAbdullahi** [comment] 2024-07-02 20:24
@divine-comedian 
Thanks to @maryjaf she shared some tokens in OP-Sepolia and I had 2 XDAI shared by MoeNick lastweek.
So I was able to complete Test for these two networks successfully and they work as expected

Gnosis chain

-  projects count : Pass
- donors count: Pass
- donations count: Pass
- total usd value donations count: Pass

Optimism-sepolia
- projects count: Pass
-  donors count: Pass
-  donations count: Pass
-  total usd value donations count: Pass

**Comment by LatifatAbdullahi** [comment] 2024-07-03 13:47
@divine-comedian 

****Base  sepolia**
 -projects count: Fail
 -donors count : Fail
 -donations count: Fail
 -total usd value donations count: Fail

**Polygon mainnet**
- projects count: Pass
- donors count: Pass
- donations count: Pass
 -total usd value donations count: Pass
 
**Polygon zkevm cardona**
- projects count : Fail
- donors count: Fail
- donations count: Fail
- total usd value donations count: Fail

**Comment by LatifatAbdullahi** [comment] 2024-07-03 15:05
@divine-comedian 
After a successful Donation to a new Project using Solana Network
![sol](https://github.com/Giveth/analytics-dashboard/assets/112261242/cce00059-160f-46a2-9e06-c370ca12f6a4)


**Solana**
-projects count : Fail
![pcc](https://github.com/Giveth/analytics-dashboard/assets/112261242/2f05da61-6992-4fb1-9b5a-7d3fece95bcf)

-donors count: Fail 
![solana Project donor](https://github.com/Giveth/analytics-dashboard/assets/112261242/810d7867-4559-4392-92f0-19abbbd201ff)

 -donations count: Fail
 
![solanaDDonations count](https://github.com/Giveth/analytics-dashboard/assets/112261242/58a919d7-3ea3-41bf-8311-00d16e1ab899)

 -total usd value donations count: Fail
 
![SolanaTotalDonations  Count](https://github.com/Giveth/analytics-dashboard/assets/112261242/286b182c-68b7-4cb4-8061-1754115cce07)

**Comment by LatifatAbdullahi** [comment] 2024-07-03 16:07
@divine-comedian 

**ARBITRUM SEPOLIA**
After a successful donation to a new Project
![ar](https://github.com/Giveth/analytics-dashboard/assets/112261242/8af83b5b-efec-4540-a473-84ee5e97a165)

-projects count : Fail
-donors count: Fail
-donations count: Fail
-total usd value donations count: Fail


projects count : Fail
![arb](https://github.com/Giveth/analytics-dashboard/assets/112261242/7c4009cb-f8db-426c-ba52-bac85e88ef82)


-donors count: Fail
![dc](https://github.com/Giveth/analytics-dashboard/assets/112261242/9e54111e-9616-4872-a8ea-27a4359750dc)


-donations count: Fail
![rt](https://github.com/Giveth/analytics-dashboard/assets/112261242/55e15ea3-aca0-4097-aa0d-4771724858a2)

-total usd value donations count: Fail

![td](https://github.com/Giveth/analytics-dashboard/assets/112261242/bd378acc-4bf0-45ff-8ca6-b7b2e549f85b)

**Comment by ae2079** [comment] 2024-07-03 21:31
@LatifatAbdullahi 
I think the last two comments were not a bug, because you used test-net and the network ID of test-net is different from the main-net

**Comment by LatifatAbdullahi** [comment] 2024-07-04 10:03
@ae2079  Alright thanks for the info.

@divine-comedian  For Solana, it means I have to test with "Solana" and not "Solana Devnet". If correct, I would need tokens for Solana, the amount I currently have cant be donated, it returns "Insufficient fund"

For "Arbitrum Sepolia" I am quite confused, which Network should I use instead?

**Comment by LatifatAbdullahi** [comment] 2024-07-04 10:56
@divine-comedian 

Test update on "**ETHEREUM CLASSIC MORDOR**"

I succesfully donated to a new Project, there was a confirmation modal, then another modal with "Transaction failed" poped-up
The tokens have bee deducted from the wallet, but no donations were registered, so I cant tell if the status of the Analystic dashboard just yet.
 
![image](https://github.com/Giveth/analytics-dashboard/assets/112261242/74392f1a-ec89-432d-9aef-87f152e42cb0)


The deductions from the wallet

![ethe](https://github.com/Giveth/analytics-dashboard/assets/112261242/c0c9c6f0-2b81-4f18-89da-88d2edc19571)

**Comment by LatifatAbdullahi** [comment] 2024-07-04 15:46
@divine-comedian @ae2079 
SOLANA

After successfully donating to a project,  there is no record of the donation, also no deduction from the Solana Wallet.
Note: I have made two successful donations with no record of it, including on the Giveth Analytics board

![image](https://github.com/Giveth/analytics-dashboard/assets/112261242/571bd5b9-21f3-48c7-981e-4b75c2e502ec)


The donations were made to this project: 
GreatProjectsLat

**Comment by divine-comedian** [comment] 2024-07-04 17:50
> @divine-comedian @ae2079 SOLANA
> 
> After successfully donating to a project, there is no record of the donation, also no deduction from the Solana Wallet. Note: I have made two successful donations with no record of it, including on the Giveth Analytics board
> 
> ![image](https://private-user-images.githubusercontent.com/112261242/345886568-571bd5b9-21f3-48c7-981e-4b75c2e502ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxMTUzMjIsIm5iZiI6MTcyMDExNTAyMiwicGF0aCI6Ii8xMTIyNjEyNDIvMzQ1ODg2NTY4LTU3MWJkNWI5LTIxZjMtNDhjNy05ODFlLTRiNzVjMmU1MDJlYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNFQxNzQzNDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YTZiZmY5OThjMjY3Y2M3NDRhZmYyMjJlOTUxMDVkNTBlZmQyOGM1YzkyNzFhODMxZjAyMDAzNzBkOTFjYzk4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.eMepLO2-kh-bKvq-OMK1y0kk5b47xac_g3dGQZnbcx0)
> 
> The donations were made to this project: GreatProjectsLat

This won't work - because donations made on unsupported networks won't be registered correctly by the dapp... 

@ae2079 we need to fix the staging analytics dashboard so it correctly looks at all test networks and not arbitrarily looking at production networks - otherwise testing will be challenging since the dapp is not setup for these things and unexpected things will happen.

**Comment by LatifatAbdullahi** [comment] 2024-07-04 18:32
@divine-comedian 

CELO ALFAJORES
Donation to the project was successful, the record is registered in the Project
 but no reflection in the Analytics board as well.

![clo](https://github.com/Giveth/analytics-dashboard/assets/112261242/431690ec-6def-4be8-914c-ca279e531045)

**Comment by ae2079** [comment] 2024-07-08 19:08
I changed the networkIds for the staging as follows:
arbitrum -> arbitrum sepolia
optimism -> optimism sepolia
base -> base sepolia
zkEVM -> zkEVM cardona
celo -> celo alfajores
solana -> solana testnet
ETC -> mordor ETC testnet
note that this changes are only for the development environment and for the production, we still using mainnets
@divine-comedian @LatifatAbdullahi

**Comment by divine-comedian** [comment] 2024-07-08 21:18
OK, @LatifatAbdullahi  can you retest then arb sepolia and solana devnet - it will be helpful for you to summarize what isn't working in a single clear comment

**Comment by LatifatAbdullahi** [comment] 2024-07-09 07:42
Okay, got it!

**Comment by LatifatAbdullahi** [comment] 2024-07-09 17:57
@divine-comedian @ae2079 

This what I experience when Trying to donate to a project; I tried multiple times thinking it was my network but still same result
https://drive.google.com/file/d/1wnJgSSmzR8wDktZOedln84DAISeGUZbx/view?usp=sharing

![sy](https://github.com/Giveth/analytics-dashboard/assets/112261242/b44e82a6-8628-477b-b77f-c5134797cf2e)


When I was finally able to click on the donation button, the donation kept failing continously; Here is another video for this behaviour
https://drive.google.com/file/d/1N_kUMnU1kn-W5BURAdCxy7Gk3j9L7AMG/view?usp=sharing

**Comment by divine-comedian** [comment] 2024-07-09 19:46
I can confirm I also get the second error, this is **very bad** because now nobody can make donations on staging! 


https://github.com/Giveth/analytics-dashboard/assets/67759413/f977afad-e861-49b5-bfa7-22721e4c843e

**Comment by ae2079** [comment] 2024-07-09 20:27
> I can confirm I also get the second error, this is **very bad** because now nobody can make donations on staging!
> Screencast.2024-07-09.13.45.56.mp4

I will fix it as soon as possible, I'm on it

**Comment by kkatusic** [comment] 2024-07-09 20:46
> > I can confirm I also get the second error, this is **very bad** because now nobody can make donations on staging!
> > Screencast.2024-07-09.13.45.56.mp4
> 
> I will fix it as soon as possible, I'm on it

I was also checking, this is happen when FE call action _** DonationsByProjectId**_, it is problem on BE, if you @ae2079 find solution ping me I will check it and approve it.

**Comment by ae2079** [comment] 2024-07-09 21:43
> > > I can confirm I also get the second error, this is **very bad** because now nobody can make donations on staging!
> > > Screencast.2024-07-09.13.45.56.mp4
> > 
> > 
> > I will fix it as soon as possible, I'm on it
> 
> I was also checking, this is happen when FE call action _** DonationsByProjectId**_, it is problem on BE, if you @ae2079 find solution ping me I will check it and approve it.

It looks like the migration do not change the database schema on staging data base, and I add the columns manually and now it works
![Screenshot 2024-07-10 010339](https://github.com/Giveth/analytics-dashboard/assets/65724329/aae77df4-d9ff-4754-aabf-725ffe2d30d7)
I check the pipeline and in this, it ran migration successfully but I don't know why it didn't affect staging database

**Comment by ae2079** [comment] 2024-07-09 21:43
@divine-comedian @LatifatAbdullahi 
now, you may be able to continue testing

**Comment by kkatusic** [comment] 2024-07-09 21:57
> @divine-comedian @LatifatAbdullahi now, you may be able to continue testing

Excellent @ae2079 , thx for fast fixing ;)

**Comment by LatifatAbdullahi** [comment] 2024-07-10 08:48
@divine-comedian @ae2079 
Test completed

Donation using both Arbitrum Sepolia and Solana Devnet were successful


**Arbitrum Sepolia**

Project count: Pass
Donors count: Pass
Donation count: Pass
Total Donations: Pass


**Solana Devnet**

Project count: Fail
Donors count: Fail
Donation count: Fail
Total Donations: Fail

**Comment by LatifatAbdullahi** [comment] 2024-07-10 08:53
Also, after  successfully donating with Solana Devnet, there is no record of the donation in that particular project

**Comment by ae2079** [comment] 2024-07-10 13:53
> Also, after successfully donating with Solana Devnet, there is no record of the donation in that particular project

@divine-comedian 
I think the Solana network is not available in the staging at all (both the main net and test net), because for both of them, the donation record did not appear after the donation to the project. Am I right?

**Comment by divine-comedian** [comment] 2024-07-10 16:17
OK so from Latifat's test results we can see the following networks are failing the tests

- Base sepolia
- Polygon zkevm cardona
- Celo Alfjores
- Ethereum Classic
- Solana Devnet

@ae2079 - You'll need to investigate why these networks are not being captured by the analytics dashboard on staging. For Solana devent we'll need to find out why the network integration appears broken, as you mentioned in your previous comment.

**Comment by ae2079** [comment] 2024-07-10 17:02
> OK so from Latifat's test results we can see the following networks are failing the tests
> 
>     * Base sepolia
> 
>     * Polygon zkevm cardona
> 
>     * Celo Alfjores
> 
>     * Ethereum Classic
> 
>     * Solana Devnet
> 
> 
> @ae2079 - You'll need to investigate why these networks are not being captured by the analytics dashboard on staging. For Solana devent we'll need to find out why the network integration appears broken, as you mentioned in your previous comment.

@LatifatAbdullahi 
Did you test these networks after the last change?
I think after the last change the problem should be resolved. (except Solana, who had a problem in donation on the staging)

**Comment by LatifatAbdullahi** [comment] 2024-07-10 17:16
> OK, @LatifatAbdullahi can you retest then arb sepolia and solana devnet - it will be helpful for the developer if you could summarize what isn't working from all test cases on all networks in a single clear comment

@ae2079 
I retested both Arbitrum Sepolia and Solana Devnet...based on this comment...thought those were the only two to be tested which I worked on.

If youre saying the rest are also ready then I will check them out as well and leave feedback on them here.

**Comment by LatifatAbdullahi** [comment] 2024-07-10 18:02
@divine-comedian  @ae2079 

Test update

Base sepolia
-projects count: Pass
-donors count : Pass
-donations count: Pass
-total usd value donations count: Pass

Polygon zkevm cardona

projects count : Pass
donors count: Pass
donations count:Pass
total usd value donations count:Pass
Celo Alfjores

projects count : Pass
donors count: Pass
donations count Pass
total usd value donations count:Pass

**Comment by LatifatAbdullahi** [comment] 2024-07-10 18:05
@divine-comedian 

I need some test token to test Ethereum classic mordor network, I currently have 0.00002 and I cant donate with that as I do not have enough to pay for transaction fee
![image](https://github.com/Giveth/analytics-dashboard/assets/112261242/29f60f96-2114-4023-a0bd-c4b896e0a175)

**Comment by LatifatAbdullahi** [comment] 2024-07-11 09:02
@divine-comedian @ae2079 

![dn](https://github.com/Giveth/analytics-dashboard/assets/112261242/aa1ac531-2e5d-486f-aa82-25b1cd387efe)

I have made multiple donations in Ethereum Classic Mordor Network, although they were successful, they all show pending here and also does not reflect in the Analytics board.

**Comment by ae2079** [comment] 2024-07-17 21:50
@divine-comedian 
now this feature is enabled in the production, so I think if there is no problem, we can consider it as Done.

**Comment by divine-comedian** [comment] 2024-07-17 22:00
@LatifatAbdullahi - Can you test this feature out on production with Solana mainnet and ETC mainnet? I will provide you with some test tokens. If these two networks pass we should be able to call this done.

**Comment by LatifatAbdullahi** [comment] 2024-07-18 15:02
@ae2079 
Please kindly drop the link for the Analytics board for production or is is same link as staging?

**Comment by ae2079** [comment] 2024-07-18 21:16
> @ae2079 Please kindly drop the link for the Analytics board for production or is is same link as staging?

Sorry, I missed that

**Closed** 2024-07-19 13:29 UTC
Labels: P2, Analytics
